#!/usr/bin/env lua
-------------------------------------------------------------------------------
-- Core: Process db and src directory to create a result in a 'public' directory
-- - get libraries
-- - initialize configuration
-- - prepare the location
-- - copy CSS files
-- - prepare some translations for templates
-- - create eli's badge
-- - create sidebar
-- - create searchbar
-- - create introduction/conclusion paragraphs
-- - create about's page
-- - copy static directory
-- - parse db files
-- - create each post file
-- - create post index file
-- - create each tag file
-- - create tag index file
-- - create homepage
-- - delete temporary files
-- @author Olivier DOSSMANN
-- @copyright Olivier DOSSMANN
-------------------------------------------------------------------------------

--[[ Variables ]]--
-- vim:expandtab:smartindent:tabstop=2:softtabstop=2:shiftwidth=2:
